export type Note = { t: string; c: string; tr: string; q: string; qt: string };

export const W4: Note[] = [
  { t: "プライドが高っ♪",                                 c: "ny",    tr: "My pride is sky high ♪",                          q: "プライドって、あなたを守ってる？邪魔してる？",       qt: "Does pride protect you — or hold you back?" },
  { t: "金がない",                                         c: "nb",    tr: "No money",                                        q: "お金がないと気づいた時、何を考える？",               qt: "What goes through your mind when you realize you have no money?" },
  { t: "えーけど私はそれでも大丈夫だと思う",               c: "ng",    tr: "Like, but I think I'll be okay anyway",           q: "「大丈夫」って言い聞かせてる自分、気づいてた？",     qt: "Did you notice yourself saying 'I'm okay' just to believe it?" },
  { t: "利き腕が左だと",                                   c: "no",    tr: "That my dominant hand is my left",                q: "自分について最近気づいた意外な事実は？",             qt: "What's a surprising fact you recently discovered about yourself?" },
  { t: "どれだけ勉強することが大事だと思っていたか",       c: "ny",    tr: "How much I thought studying was everything",       q: "昔「絶対大事」と思ってたこと、今も同じ？",           qt: "Something you once thought was everything — do you still feel that way?" },
  { t: "理不尽が多い",                                     c: "np",    tr: "There's so much unfairness",                      q: "理不尽に気づいた時、どうしてる？",                   qt: "What do you do when you notice something's just not fair?" },
  { t: "真剣に思ってない",                                 c: "nb",    tr: "I don't actually take it seriously",              q: "本当は真剣じゃないのに、真剣なふりしてることある？", qt: "Do you ever pretend to care more than you actually do?" },
  { t: "それな？",                                         c: "ny",    tr: "Right?",                                          q: "最近「それな！」って思った瞬間は？",                 qt: "When did something recently just totally resonate with you?" },
  { t: "図書室が大好き",                                   c: "ng",    tr: "I love the library",                              q: "好きな場所って、いつ気づいた？",                     qt: "When did you realize you had a favorite place?" },
  { t: "ハンターハンターおもしろい♡",                      c: "no",    tr: "Hunter x Hunter is so good ♡",                    q: "最近ハマったものを、誰かに話した？",                 qt: "Have you told anyone about your latest obsession?" },
  { t: "ボードに貼れてる",                                 c: "np",    tr: "I'm actually putting something on the board",     q: "自分が参加してることに気づく瞬間って？",             qt: "When do you notice that you're actually part of something?" },
  { t: "愛とお金が大事",                                   c: "ny",    tr: "Love and money matter",                           q: "愛とお金、どっちが先に気づいた？",                   qt: "Which did you notice first — love or money?" },
  { t: "1年生仲良さそう",                                  c: "nb",    tr: "1st years seem so close",                         q: "他のグループを見て、何か気づいたことある？",         qt: "Has watching another group ever made you notice something?" },
  { t: "スーツが似合わない",                               c: "ng",    tr: "Suits don't suit me",                             q: "自分の見た目について、最近気づいたことは？",         qt: "What's something about your appearance you've recently noticed?" },
  { t: "何かがおかしい！？",                               c: "np",    tr: "Something is off!?",                              q: "「あれ、おかしくない？」って思ったのはどんな時？",   qt: "When did you last think — wait, something's not right here?" },
  { t: "大学で友達できないこと",                           c: "nb",    tr: "That I can't make friends at uni",                q: "友達ができないと気づいた時、どんな気持ちだった？",   qt: "How did it feel when you realized you weren't making friends?" },
  { t: "年齢と体脂肪が比例してる…",                       c: "no",    tr: "Age and body fat are proportional...",             q: "身体の変化に気づいた時、どう受け止めた？",           qt: "How did you take it when you noticed your body changing?" },
  { t: "そんなに食べてないのに",                           c: "ny",    tr: "Even though I'm not eating that much",            q: "身体の声に気づいてる？",                             qt: "Are you listening to what your body is telling you?" },
  { t: "ここで話す方が楽しいと気づいてしまった",           c: "ng",    tr: "I noticed I enjoy talking here more",             q: "「あ、楽しいな」って気づく瞬間、どんな時？",         qt: "When do you catch yourself thinking — oh, I'm actually enjoying this?" },
  { t: "ウクレレ アリ？",                                  c: "no",    tr: "Wait — ukulele actually works?",                  q: "予想外にハマったもの、最近ある？",                   qt: "Is there something you got into recently that surprised you?" },
  { t: "生活習慣が乱れてる",                               c: "np",    tr: "My daily routine is a mess",                      q: "いつから乱れたか、気づいてた？",                     qt: "Did you notice when things started falling apart?" },
  { t: "老人は寒い日も歩く",                               c: "ny",    tr: "Old people walk in cold weather",                 q: "年上の人の行動で、何か気づかされたことは？",         qt: "Has an older person's behavior ever made you realize something?" },
  { t: "アルコール アレルギーだった",                      c: "nb",    tr: "I have an alcohol allergy",                       q: "自分の身体について、最近初めて気づいたことは？",     qt: "What's something about your body you only just discovered?" },
  { t: "人に言いにくいけど、それが幸せだった",             c: "ng",    tr: "Hard to say, but that was happiness",             q: "言えない幸せって、あなたにある？",                   qt: "Is there a happiness you can't quite say out loud?" },
  { t: "時間がたりない！",                                 c: "no",    tr: "There's not enough time!",                        q: "時間が足りないと気づく瞬間、何してる？",             qt: "What are you doing when you realize there's no time left?" },
  { t: "えがさん神",                                       c: "ny",    tr: "Ega-san is a god",                                q: "誰かの凄さに気づいた瞬間は？",                       qt: "When did you last catch yourself thinking — wow, they're incredible?" },
  { t: "余裕がない！！",                                   c: "np",    tr: "I have no bandwidth!!",                           q: "余裕がなくなるの、気づいた時には遅い？",             qt: "Is it always too late when you finally notice you've hit your limit?" },
  { t: "何かを大切にしろ",                                 c: "nb",    tr: "Cherish something",                               q: "最近、大切にしてないなと気づいたものは？",           qt: "What have you recently realized you've been neglecting?" },
  { t: "We're not as important as we think",               c: "ng en", tr: "自分たちは思ってるほど大切じゃない",              q: "Have you ever caught yourself thinking you matter more than you do?", qt: "自分の重要さを過大評価してたと気づいたことある？" },
  { t: "people only care about themselves",                c: "no en", tr: "人は自分のことしか考えていない",                  q: "How did it feel when you realized that?",            qt: "それを気づいた時、どんな気持ちだった？" },
  { t: "I forget about other people's lives",              c: "ny en", tr: "他の人の人生のことを忘れてしまう",                q: "When do you find yourself thinking about someone else's life?", qt: "誰かの人生を思い出す瞬間って、どんな時？" },
  { t: "Friends don't exist for me",                       c: "np en", tr: "私には友達がいない",                              q: "What does friendship actually mean to you?",         qt: "友達の定義って、自分にとって何だろう？" },
  { t: "Life is Unfair",                                   c: "nb en", tr: "人生は不公平",                                    q: "What did you do the moment you realized life just isn't fair?", qt: "不公平だと気づいた瞬間、何をした？" },
];

export const W3: Note[] = [
  { t: "笑顔を見た時",                             c: "ny",    tr: "When I see their smile",                              q: "最後に誰かの笑顔にきゅんとしたのは？",               qt: "When did someone's smile last make your heart skip?" },
  { t: "When I feel loved",                        c: "np en", tr: "愛されていると感じる時",                               q: "When did you last truly feel loved?",                 qt: "最後に心から愛されてると感じたのはいつ？" },
  { t: "ギャップを感じたとき",                     c: "ny",    tr: "When I sense a surprising side",                      q: "最近、ギャップにやられた瞬間は？",                   qt: "When were you last caught off guard by someone's unexpected side?" },
  { t: "Love at first sight",                      c: "nb en", tr: "一目惚れ",                                            q: "Have you ever experienced love at first sight?",     qt: "一目惚れを経験したことある？" },
  { t: "頑張っている姿を見た時",                   c: "ny",    tr: "When I see them working hard",                        q: "最近、誰かが頑張る姿を見て何か感じた？",             qt: "Has someone working hard recently moved you in some way?" },
  { t: "When they remember what I like",           c: "np en", tr: "好きなものを覚えてくれている時",                      q: "What's one small thing you'd want someone to remember about you?", qt: "あなたのことを覚えていてほしい、小さなことは何？" },
  { t: "自然と目立つとき",                         c: "ng",    tr: "When they naturally stand out",                       q: "自然と目が行く人って、どんな人？",                   qt: "What kind of person naturally draws your attention?" },
  { t: "一緒にいて楽しいとき",                     c: "no",    tr: "When I enjoy being with them",                        q: "一緒にいて一番楽しい時間って、どんな時？",           qt: "What's the best time you've had just being with someone?" },
  { t: "The moment she smiled",                    c: "nb en", tr: "彼女が笑った瞬間",                                    q: "Whose smile stays with you?",                        qt: "誰の笑顔が、頭から離れない？" },
  { t: "When they wrote me a song",                c: "no en", tr: "歌を書いてくれた時",                                  q: "What's the most personal thing someone has ever done for you?", qt: "誰かにしてもらった中で、一番個人的なことは？" },
  { t: "Seeing someone differently than before",   c: "ny en", tr: "以前と違って見えた時",                                q: "Has someone ever surprised you by being completely different than you thought?", qt: "思っていたのと全然違うと気づいて、驚いたことある？" },
  { t: "顔・笑顔",                                 c: "ny",    tr: "Their face / their smile",                            q: "どんな顔に、ついつい目が行く？",                     qt: "What kind of face do you keep coming back to?" },
  { t: "優しさ",                                   c: "np",    tr: "Their kindness",                                      q: "忘れられない、誰かの優しさはある？",                 qt: "Is there a moment of kindness you can't forget?" },
  { t: "雰囲気・見た目",                           c: "nb",    tr: "Their vibe / appearance",                             q: "第一印象って、どれくらい当たってる？",               qt: "How often does your first impression turn out to be right?" },
  { t: "男っぽさ / 笑顔がスキ",                   c: "ny",    tr: "Masculinity / love their smile",                      q: "「いいな」と思う瞬間って、どんな時？",               qt: "What's the moment when you think — yeah, they're something special?" },
  { t: "自立している人",                           c: "ng",    tr: "Someone independent",                                 q: "自立してると感じる人の、どこが好き？",               qt: "What do you love about someone who stands on their own?" },
  { t: "筋肉",                                     c: "no",    tr: "Muscles",                                             q: "見た目で、ついつい気になったことある？",             qt: "Has someone's appearance ever caught you off guard?" },
  { t: "黒髪・ロング",                             c: "ny",    tr: "Black hair, long hair",                               q: "外見で、一番ひかれるのはどこ？",                     qt: "What physical feature attracts you most?" },
  { t: "いっぱい食べる人",                         c: "nb",    tr: "Someone who eats a lot",                              q: "食べてる姿ってなんか好きじゃない？",                 qt: "Don't you just love watching someone eat with enthusiasm?" },
  { t: "Just feeling",                             c: "np en", tr: "なんとなく",                                          q: "Have you ever fallen for someone with no idea why?", qt: "理由もわからないまま、誰かを好きになったことある？" },
  { t: "なんとなく",                               c: "ny",    tr: "Just... somehow",                                     q: "「なんとなくいいな」って感じたこと、最近ある？",     qt: "Have you recently felt drawn to someone for no clear reason?" },
  { t: "Can't answer when, but I know when I do",  c: "nb en", tr: "いつとは言えないけど、その時はわかる",                q: "How do you know when you really like someone?",      qt: "本当に好きだって、どうやってわかる？" },
  { t: "推し ♡",                                   c: "ny",    tr: "My fave ♡",                                           q: "今の推しは？",                                       qt: "Who's your current fave?" },
  { t: "Don't fall in love",                       c: "ng en", tr: "恋はしない",                                          q: "Is protecting yourself from love ever the right choice?", qt: "恋から自分を守ることが、正解な時ってある？" },
  { t: "ギャップ",                                 c: "no",    tr: "A surprising side of them",                           q: "どんなギャップに弱い？",                             qt: "What kind of unexpected side makes you fall a little?" },
  { t: "They fall in love with me!",               c: "np en", tr: "向こうが私を好きになった時！",                        q: "Does being liked by someone change how you see them?", qt: "好かれると、相手の見え方が変わる？" },
  { t: "When I feel familiar",                     c: "nb en", tr: "親しみを感じる時",                                    q: "What makes someone feel like home?",                 qt: "何があると、その人がホームみたいに感じる？" },
  { t: "元気にしてくれる人",                       c: "no",    tr: "Someone who lifts my spirits",                        q: "あなたを元気にしてくれるのは、どんな存在？",         qt: "What kind of person lifts you up?" },
  { t: "優しくされたとき",                         c: "ny",    tr: "When they're kind to me",                             q: "最近、誰かに優しくされてうれしかったことは？",       qt: "When were you last genuinely touched by someone's kindness?" },
  { t: "When this person consistently notices me", c: "np en", tr: "いつも気にかけてくれる時",                            q: "Do you notice the people who notice you?",           qt: "あなたに気づいてくれる人に、気づいてる？" },
  { t: "緊張がほぐれた時",                         c: "nb",    tr: "When I feel relaxed around them",                     q: "緊張がほぐれたとき、何か気づいたことある？",         qt: "What did you notice when you finally relaxed around someone?" },
  { t: "Think about them a lot",                   c: "ng en", tr: "ついたくさん考えてしまう",                            q: "Is there someone you keep thinking about lately?",   qt: "最近、頭から離れない人がいる？" },
  { t: "夢の中にしょっちゅう出てくる",             c: "ny",    tr: "They keep appearing in my dreams",                    q: "夢に出てくる人って、やっぱり気になってる？",         qt: "If someone keeps showing up in your dreams, does that mean something?" },
  { t: "That's my first thought in the morning",   c: "np en", tr: "朝一番に思い浮かぶ",                                  q: "What's the first thing on your mind when you wake up?", qt: "目覚めた瞬間、最初に浮かぶのは何？" },
];

export const W2: Note[] = [
  { t: "信用を失うから",                           c: "np",    tr: "Because it breaks trust",                            q: "誰かの嘘に気づいたとき、どう感じた？",               qt: "How did it feel when you caught someone in a lie?" },
  { t: "Except when it protects others",           c: "np en", tr: "他者を守る場合は別",                                  q: "Can you think of a lie that was actually kind?",     qt: "本当に優しかった嘘を、思いつける？" },
  { t: "そもそも必要ない",                         c: "np",    tr: "It's not necessary in the first place",               q: "嘘をつかずに生きたら、どうなると思う？",             qt: "What would life look like if you never told a lie?" },
  { t: "うそをして生きたくない",                   c: "np",    tr: "I don't want to live a lie",                          q: "正直でいることが、つらかった経験は？",               qt: "When has being honest been genuinely painful?" },
  { t: "自分を傷つけることになる",                 c: "np",    tr: "It ends up hurting yourself",                         q: "ついた嘘が、あとで自分に返ってきたことある？",       qt: "Has a lie you told ever come back to hurt you?" },
  { t: "Lying bad",                                c: "np en", tr: "嘘はダメ",                                            q: "Is there a lie you regret telling?",                 qt: "後悔している嘘は、ある？" },
  { t: "White lie is OK",                          c: "ny en", tr: "優しい嘘はOK",                                        q: "Have you ever told a white lie to protect someone?", qt: "誰かを守るための優しい嘘、ついたことある？" },
  { t: "It depends on the situation",              c: "ny en", tr: "状況による",                                          q: "What situation would make lying acceptable to you?", qt: "どんな状況なら、嘘が許されると思う？" },
  { t: "Depends on context and intention",         c: "ny en", tr: "文脈と意図次第",                                      q: "Does the reason for a lie change whether it's wrong?", qt: "嘘の理由によって、それが悪いかどうか変わる？" },
  { t: "どんな目的で、誰の幸せのため",             c: "ny",    tr: "For what purpose, for whose happiness",               q: "誰かのためについた嘘、後悔してない？",               qt: "Have you ever regretted a lie you told for someone else?" },
  { t: "Context matters",                          c: "ny en", tr: "状況が大事",                                          q: "When has the situation changed whether something felt like a lie?", qt: "状況によって、嘘かどうかの感覚が変わった経験は？" },
  { t: "What is a lie?",                           c: "ny en", tr: "そもそも嘘って何？",                                  q: "Is hiding the truth the same as lying?",             qt: "真実を隠すのも、嘘をつくことと同じ？" },
  { t: "その嘘が良いもの？悪いもの？個人の感想",   c: "ny",    tr: "Good or bad lie? That's personal.",                   q: "嘘の良し悪しって、誰が決めるんだろう？",             qt: "Who decides whether a lie is good or bad?" },
  { t: "人を幸せにするなら OK",                    c: "ng",    tr: "OK if it makes someone happy",                        q: "相手を幸せにする嘘、ついたことある？",               qt: "Have you ever lied to make someone genuinely happier?" },
  { t: "嘘をつかない人はいない",                   c: "ng",    tr: "Nobody is free from lies",                            q: "嘘を全くつかない人って、いると思う？",               qt: "Do you think anyone is completely free from lying?" },
  { t: "自分を守るため",                           c: "ng",    tr: "To protect yourself",                                 q: "自分を守るために嘘をついた経験は？",                 qt: "Have you ever lied to protect yourself?" },
  { t: "Lying good",                               c: "ng en", tr: "嘘は良いこと",                                        q: "Has a lie ever actually made things better?",        qt: "嘘をついた結果、本当に良くなったことある？" },
  { t: "You can't be honest about everything",     c: "ng en", tr: "なんでも正直にはできない",                            q: "What's something you've never been fully honest about?", qt: "完全には正直になれていないこと、ある？" },
  { t: "自分の身を守ることができる",               c: "ng",    tr: "You can protect yourself",                            q: "正直でいることより大切なことって何だろう？",         qt: "Is there something more important than always being honest?" },
  { t: "人を幸せにするため",                       c: "ng",    tr: "To make someone happy",                               q: "あなたにとって「いい嘘」ってどんな嘘？",             qt: "What would a 'good lie' look like to you?" },
];

export const W1: Note[] = [
  { t: "Trauma & Fear",                                      c: "nb en", tr: "トラウマと恐怖",                             q: "Is there a fear that makes you more judgmental?",    qt: "より批判的にさせる恐怖って、ある？" },
  { t: "They're afraid / defensive",                         c: "nb en", tr: "怖いから、防衛している",                     q: "When do you judge others to protect yourself?",      qt: "自分を守るために他者を評価するのは、どんな時？" },
  { t: "To protect oneself",                                 c: "nb en", tr: "自分を守るため",                             q: "Have you ever judged someone just to feel safer?",   qt: "安心するために誰かを評価したことある？" },
  { t: "自分を傷つけたくないから",                           c: "nb",    tr: "Because they don't want to be hurt",         q: "誰かを評価することで、自分を守ろうとしたことある？", qt: "Have you ever judged someone as a way of protecting yourself?" },
  { t: "Because I'm right",                                  c: "nb en", tr: "自分が正しいから",                           q: "When were you last certain you were right about someone?", qt: "最後に「自分が正しい」と確信したのはいつ？" },
  { t: "It's not what I would do",                           c: "nb en", tr: "自分ならそうしないから",                     q: "How often do you judge people for doing things differently?", qt: "自分と違うやり方をしている人を、どれくらい評価してしまう？" },
  { t: "自己防衛のため",                                     c: "nb",    tr: "For self-defense",                           q: "防衛のために誰かを評価してしまうこと、ある？",       qt: "Do you sometimes judge others as a kind of self-defense?" },
  { t: "Religious conduct",                                  c: "no en", tr: "宗教的な行動規範",                           q: "How much do your values shape the way you judge others?", qt: "自分の価値観が他者への評価に与える影響、どのくらい？" },
  { t: "Due to societal norms, family, culture, media",      c: "no en", tr: "社会規範・家族・文化・メディアの影響",       q: "Which of your judgments might have come from someone else?", qt: "自分の評価の中で、誰かから受け継いだものは？" },
  { t: "Influence of their surroundings",                    c: "no en", tr: "環境の影響",                                 q: "How has your environment shaped who you judge?",     qt: "環境が、あなたの評価の仕方をどう形づくった？" },
  { t: "無意識に強制する",                                   c: "no",    tr: "Unconsciously imposing on others",           q: "自分の「普通」を押しつけてしまったこと、ある？",     qt: "Have you ever pushed your idea of 'normal' onto someone else?" },
  { t: "Just because they are different",                    c: "no en", tr: "ただ違うから",                               q: "Has something you once judged ended up changing you?", qt: "かつて評価したものが、最終的に自分を変えたことある？" },
  { t: "他者への誤解を通じて自己を確認する",                 c: "no",    tr: "Confirming oneself through misreading others", q: "誰かを誤解することで、自分について何か気づいたことある？", qt: "Have you ever learned something about yourself by misunderstanding someone?" },
  { t: "Unconscious bias",                                   c: "no en", tr: "無意識の偏見",                               q: "What's a bias you've noticed in yourself?",          qt: "自分の中で気づいた偏見って、何？" },
  { t: "Lack of empathy",                                    c: "ny en", tr: "共感力の欠如",                               q: "When do you find it hardest to empathize with someone?", qt: "誰かと共感するのが一番難しいのは、どんな時？" },
  { t: "楽しいから",                                         c: "ny",    tr: "Because it's fun",                           q: "評価することが楽しいと感じる瞬間、ある？",           qt: "Is there a moment when judging others actually feels fun?" },
  { t: "Because I'm mean",                                   c: "ny en", tr: "意地悪だから",                               q: "Have you ever judged someone and felt bad about it later?", qt: "誰かを評価して、後で後悔したことある？" },
  { t: "相対的に強さを持ちたいから",                         c: "ny",    tr: "To feel relatively stronger",                q: "誰かより上に立ちたいと感じるのは、どんな時？",       qt: "When do you feel the urge to be above someone else?" },
  { t: "公平な比較が難しいから",                             c: "ny",    tr: "Because fair comparison is hard",            q: "人を公平に見ることって、本当にできると思う？",       qt: "Do you really think it's possible to see people fairly?" },
  { t: "Don't want to mind their own business",              c: "ng en", tr: "自分のことだけ考えたくないから",             q: "Is it ever your business to judge someone else?",    qt: "他者を評価することが、自分に関係あることって本当にある？" },
  { t: "自分のアイデンティティをつくるため",                 c: "ng",    tr: "To form one's identity",                     q: "「自分らしさ」を決めるために、誰かと比べたことある？", qt: "Have you ever compared yourself to someone to figure out who you are?" },
  { t: "Cause it's fun to do with friends",                  c: "ng en", tr: "友達とやると楽しいから",                     q: "Does judging people feel different when you're with others?", qt: "一人でいる時と、友達と一緒にいる時で評価の感じ方が違う？" },
  { t: "他人に影響を与えたいから",                           c: "ng",    tr: "To influence others",                        q: "誰かの見方を変えようとしたことある？",               qt: "Have you ever tried to change how someone sees another person?" },
  { t: "知らないから / わかんないから",                      c: "ng",    tr: "Because they don't know / don't get it",     q: "知らないから評価してしまう——どうすれば変えられる？", qt: "Judging what you don't know — how do you think you'd change that?" },
  { t: "Because they honestly understand some things",       c: "ng en", tr: "本当に理解できることがあるから",             q: "When is judging someone actually helpful?",          qt: "誰かを評価することが、本当に役に立つのはどんな時？" },
  { t: "For motivation",                                     c: "ng en", tr: "モチベーションのため",                       q: "Has being judged ever pushed you to grow?",          qt: "評価されることで成長できたことある？" },
  { t: "利用したいから",                                     c: "ng",    tr: "To use them",                                q: "人間関係で、使う・使われるって感じたことある？",     qt: "Have you ever felt used — or used someone — in a relationship?" },
];
