export type Note = { t: string; c: string; tr: string; q: string };

export const W4: Note[] = [
  { t: "プライドが高っ♪",                                 c: "ny",    tr: "My pride is sky high ♪",                          q: "プライドって、あなたを守ってる？邪魔してる？" },
  { t: "金がない",                                         c: "nb",    tr: "No money",                                        q: "お金がないと気づいた時、何を考える？" },
  { t: "えーけど私はそれでも大丈夫だと思う",               c: "ng",    tr: "Like, but I think I'll be okay anyway",           q: "「大丈夫」って言い聞かせてる自分、気づいてた？" },
  { t: "利き腕が左だと",                                   c: "no",    tr: "That my dominant hand is my left",                q: "自分について最近気づいた意外な事実は？" },
  { t: "どれだけ勉強することが大事だと思っていたか",       c: "ny",    tr: "How much I thought studying was everything",       q: "昔「絶対大事」と思ってたこと、今も同じ？" },
  { t: "理不尽が多い",                                     c: "np",    tr: "There's so much unfairness",                      q: "理不尽に気づいた時、どうしてる？" },
  { t: "真剣に思ってない",                                 c: "nb",    tr: "I don't actually take it seriously",              q: "本当は真剣じゃないのに、真剣なふりしてることある？" },
  { t: "それな？",                                         c: "ny",    tr: "Right?",                                          q: "最近「それな！」って思った瞬間は？" },
  { t: "図書室が大好き",                                   c: "ng",    tr: "I love the library",                              q: "好きな場所って、いつ気づいた？" },
  { t: "ハンターハンターおもしろい♡",                      c: "no",    tr: "Hunter x Hunter is so good ♡",                    q: "最近ハマったものを、誰かに話した？" },
  { t: "ボードに貼れてる",                                 c: "np",    tr: "I'm actually putting something on the board",     q: "自分が参加してることに気づく瞬間って？" },
  { t: "愛とお金が大事",                                   c: "ny",    tr: "Love and money matter",                           q: "愛とお金、どっちが先に気づいた？" },
  { t: "1年生仲良さそう",                                  c: "nb",    tr: "1st years seem so close",                         q: "他のグループを見て、何か気づいたことある？" },
  { t: "スーツが似合わない",                               c: "ng",    tr: "Suits don't suit me",                             q: "自分の見た目について、最近気づいたことは？" },
  { t: "何かがおかしい！？",                               c: "np",    tr: "Something is off!?",                              q: "「あれ、おかしくない？」って思ったのはどんな時？" },
  { t: "大学で友達できないこと",                           c: "nb",    tr: "That I can't make friends at uni",                q: "友達ができないと気づいた時、どんな気持ちだった？" },
  { t: "年齢と体脂肪が比例してる…",                       c: "no",    tr: "Age and body fat are proportional...",             q: "身体の変化に気づいた時、どう受け止めた？" },
  { t: "そんなに食べてないのに",                           c: "ny",    tr: "Even though I'm not eating that much",            q: "身体の声に気づいてる？" },
  { t: "ここで話す方が楽しいと気づいてしまった",           c: "ng",    tr: "I noticed I enjoy talking here more",             q: "「あ、楽しいな」って気づく瞬間、どんな時？" },
  { t: "ウクレレ アリ？",                                  c: "no",    tr: "Wait — ukulele actually works?",                  q: "予想外にハマったもの、最近ある？" },
  { t: "生活習慣が乱れてる",                               c: "np",    tr: "My daily routine is a mess",                      q: "いつから乱れたか、気づいてた？" },
  { t: "老人は寒い日も歩く",                               c: "ny",    tr: "Old people walk in cold weather",                 q: "年上の人の行動で、何か気づかされたことは？" },
  { t: "アルコール アレルギーだった",                      c: "nb",    tr: "I have an alcohol allergy",                       q: "自分の身体について、最近初めて気づいたことは？" },
  { t: "人に言いにくいけど、それが幸せだった",             c: "ng",    tr: "Hard to say, but that was happiness",             q: "言えない幸せって、あなたにある？" },
  { t: "時間がたりない！",                                 c: "no",    tr: "There's not enough time!",                        q: "時間が足りないと気づく瞬間、何してる？" },
  { t: "えがさん神",                                       c: "ny",    tr: "Ega-san is a god",                                q: "誰かの凄さに気づいた瞬間は？" },
  { t: "余裕がない！！",                                   c: "np",    tr: "I have no bandwidth!!",                           q: "余裕がなくなるの、気づいた時には遅い？" },
  { t: "何かを大切にしろ",                                 c: "nb",    tr: "Cherish something",                               q: "最近、大切にしてないなと気づいたものは？" },
  { t: "We're not as important as we think",               c: "ng en", tr: "自分たちは思ってるほど大切じゃない",              q: "自分の重要さを過大評価してたと気づいたことある？" },
  { t: "people only care about themselves",                c: "no en", tr: "人は自分のことしか考えていない",                  q: "それを気づいた時、どんな気持ちだった？" },
  { t: "I forget about other people's lives",              c: "ny en", tr: "他の人の人生のことを忘れてしまう",                q: "誰かの人生を思い出す瞬間って、どんな時？" },
  { t: "Friends don't exist for me",                       c: "np en", tr: "私には友達がいない",                              q: "友達の定義って、自分にとって何だろう？" },
  { t: "Life is Unfair",                                   c: "nb en", tr: "人生は不公平",                                    q: "不公平だと気づいた瞬間、何をした？" },
];

export const W3: Note[] = [
  { t: "笑顔を見た時",                             c: "ny",    tr: "When I see their smile",                              q: "最後に誰かの笑顔にきゅんとしたのは？" },
  { t: "When I feel loved",                        c: "np en", tr: "愛されていると感じる時",                               q: "最後に心から愛されてると感じたのはいつ？" },
  { t: "ギャップを感じたとき",                     c: "ny",    tr: "When I sense a surprising side",                      q: "最近、ギャップにやられた瞬間は？" },
  { t: "Love at first sight",                      c: "nb en", tr: "一目惚れ",                                            q: "Have you ever experienced love at first sight?" },
  { t: "頑張っている姿を見た時",                   c: "ny",    tr: "When I see them working hard",                        q: "最近、誰かが頑張る姿を見て何か感じた？" },
  { t: "When they remember what I like",           c: "np en", tr: "好きなものを覚えてくれている時",                      q: "What's one small thing you'd want someone to remember about you?" },
  { t: "自然と目立つとき",                         c: "ng",    tr: "When they naturally stand out",                       q: "自然と目が行く人って、どんな人？" },
  { t: "一緒にいて楽しいとき",                     c: "no",    tr: "When I enjoy being with them",                        q: "一緒にいて一番楽しい時間って、どんな時？" },
  { t: "The moment she smiled",                    c: "nb en", tr: "彼女が笑った瞬間",                                    q: "Whose smile stays with you?" },
  { t: "When they wrote me a song",                c: "no en", tr: "歌を書いてくれた時",                                  q: "What's the most personal thing someone has ever done for you?" },
  { t: "Seeing someone differently than before",   c: "ny en", tr: "以前と違って見えた時",                                q: "Has someone ever surprised you by being completely different than you thought?" },
  { t: "顔・笑顔",                                 c: "ny",    tr: "Their face / their smile",                            q: "どんな顔に、ついつい目が行く？" },
  { t: "優しさ",                                   c: "np",    tr: "Their kindness",                                      q: "忘れられない、誰かの優しさはある？" },
  { t: "雰囲気・見た目",                           c: "nb",    tr: "Their vibe / appearance",                             q: "第一印象って、どれくらい当たってる？" },
  { t: "男っぽさ / 笑顔がスキ",                   c: "ny",    tr: "Masculinity / love their smile",                      q: "「いいな」と思う瞬間って、どんな時？" },
  { t: "自立している人",                           c: "ng",    tr: "Someone independent",                                 q: "自立してると感じる人の、どこが好き？" },
  { t: "筋肉",                                     c: "no",    tr: "Muscles",                                             q: "見た目で、ついつい気になったことある？" },
  { t: "黒髪・ロング",                             c: "ny",    tr: "Black hair, long hair",                               q: "外見で、一番ひかれるのはどこ？" },
  { t: "いっぱい食べる人",                         c: "nb",    tr: "Someone who eats a lot",                              q: "食べてる姿ってなんか好きじゃない？" },
  { t: "Just feeling",                             c: "np en", tr: "なんとなく",                                          q: "Have you ever fallen for someone with no idea why?" },
  { t: "なんとなく",                               c: "ny",    tr: "Just... somehow",                                     q: "「なんとなくいいな」って感じたこと、最近ある？" },
  { t: "Can't answer when, but I know when I do",  c: "nb en", tr: "いつとは言えないけど、その時はわかる",                q: "How do you know when you really like someone?" },
  { t: "推し ♡",                                   c: "ny",    tr: "My fave ♡",                                           q: "今の推しは？" },
  { t: "Don't fall in love",                       c: "ng en", tr: "恋はしない",                                          q: "Is protecting yourself from love ever the right choice?" },
  { t: "ギャップ",                                 c: "no",    tr: "A surprising side of them",                           q: "どんなギャップに弱い？" },
  { t: "They fall in love with me!",               c: "np en", tr: "向こうが私を好きになった時！",                        q: "Does being liked by someone change how you see them?" },
  { t: "When I feel familiar",                     c: "nb en", tr: "親しみを感じる時",                                    q: "What makes someone feel like home?" },
  { t: "元気にしてくれる人",                       c: "no",    tr: "Someone who lifts my spirits",                        q: "あなたを元気にしてくれるのは、どんな存在？" },
  { t: "優しくされたとき",                         c: "ny",    tr: "When they're kind to me",                             q: "最近、誰かに優しくされてうれしかったことは？" },
  { t: "When this person consistently notices me", c: "np en", tr: "いつも気にかけてくれる時",                            q: "Do you notice the people who notice you?" },
  { t: "緊張がほぐれた時",                         c: "nb",    tr: "When I feel relaxed around them",                     q: "緊張がほぐれたとき、何か気づいたことある？" },
  { t: "Think about them a lot",                   c: "ng en", tr: "ついたくさん考えてしまう",                            q: "Is there someone you keep thinking about lately?" },
  { t: "夢の中にしょっちゅう出てくる",             c: "ny",    tr: "They keep appearing in my dreams",                    q: "夢に出てくる人って、やっぱり気になってる？" },
  { t: "That's my first thought in the morning",   c: "np en", tr: "朝一番に思い浮かぶ",                                  q: "What's the first thing on your mind when you wake up?" },
];

export const W2: Note[] = [
  { t: "信用を失うから",                           c: "np",    tr: "Because it breaks trust",                            q: "誰かの嘘に気づいたとき、どう感じた？" },
  { t: "Except when it protects others",           c: "np en", tr: "他者を守る場合は別",                                  q: "Can you think of a lie that was actually kind?" },
  { t: "そもそも必要ない",                         c: "np",    tr: "It's not necessary in the first place",               q: "嘘をつかずに生きたら、どうなると思う？" },
  { t: "うそをして生きたくない",                   c: "np",    tr: "I don't want to live a lie",                          q: "正直でいることが、つらかった経験は？" },
  { t: "自分を傷つけることになる",                 c: "np",    tr: "It ends up hurting yourself",                         q: "ついた嘘が、あとで自分に返ってきたことある？" },
  { t: "Lying bad",                                c: "np en", tr: "嘘はダメ",                                            q: "Is there a lie you regret telling?" },
  { t: "White lie is OK",                          c: "ny en", tr: "優しい嘘はOK",                                        q: "Have you ever told a white lie to protect someone?" },
  { t: "It depends on the situation",              c: "ny en", tr: "状況による",                                          q: "What situation would make lying acceptable to you?" },
  { t: "Depends on context and intention",         c: "ny en", tr: "文脈と意図次第",                                      q: "Does the reason for a lie change whether it's wrong?" },
  { t: "どんな目的で、誰の幸せのため",             c: "ny",    tr: "For what purpose, for whose happiness",               q: "誰かのためについた嘘、後悔してない？" },
  { t: "Context matters",                          c: "ny en", tr: "状況が大事",                                          q: "When has the situation changed whether something felt like a lie?" },
  { t: "What is a lie?",                           c: "ny en", tr: "そもそも嘘って何？",                                  q: "Is hiding the truth the same as lying?" },
  { t: "その嘘が良いもの？悪いもの？個人の感想",   c: "ny",    tr: "Good or bad lie? That's personal.",                   q: "嘘の良し悪しって、誰が決めるんだろう？" },
  { t: "人を幸せにするなら OK",                    c: "ng",    tr: "OK if it makes someone happy",                        q: "相手を幸せにする嘘、ついたことある？" },
  { t: "嘘をつかない人はいない",                   c: "ng",    tr: "Nobody is free from lies",                            q: "嘘を全くつかない人って、いると思う？" },
  { t: "自分を守るため",                           c: "ng",    tr: "To protect yourself",                                 q: "自分を守るために嘘をついた経験は？" },
  { t: "Lying good",                               c: "ng en", tr: "嘘は良いこと",                                        q: "Has a lie ever actually made things better?" },
  { t: "You can't be honest about everything",     c: "ng en", tr: "なんでも正直にはできない",                            q: "What's something you've never been fully honest about?" },
  { t: "自分の身を守ることができる",               c: "ng",    tr: "You can protect yourself",                            q: "正直でいることより大切なことって何だろう？" },
  { t: "人を幸せにするため",                       c: "ng",    tr: "To make someone happy",                               q: "あなたにとって「いい嘘」ってどんな嘘？" },
];

export const W1: Note[] = [
  { t: "Trauma & Fear",                                      c: "nb en", tr: "トラウマと恐怖",                             q: "Is there a fear that makes you more judgmental?" },
  { t: "They're afraid / defensive",                         c: "nb en", tr: "怖いから、防衛している",                     q: "When do you judge others to protect yourself?" },
  { t: "To protect oneself",                                 c: "nb en", tr: "自分を守るため",                             q: "Have you ever judged someone just to feel safer?" },
  { t: "自分を傷つけたくないから",                           c: "nb",    tr: "Because they don't want to be hurt",         q: "誰かを評価することで、自分を守ろうとしたことある？" },
  { t: "Because I'm right",                                  c: "nb en", tr: "自分が正しいから",                           q: "When were you last certain you were right about someone?" },
  { t: "It's not what I would do",                           c: "nb en", tr: "自分ならそうしないから",                     q: "How often do you judge people for doing things differently?" },
  { t: "自己防衛のため",                                     c: "nb",    tr: "For self-defense",                           q: "防衛のために誰かを評価してしまうこと、ある？" },
  { t: "Religious conduct",                                  c: "no en", tr: "宗教的な行動規範",                           q: "How much do your values shape the way you judge others?" },
  { t: "Due to societal norms, family, culture, media",      c: "no en", tr: "社会規範・家族・文化・メディアの影響",       q: "Which of your judgments might have come from someone else?" },
  { t: "Influence of their surroundings",                    c: "no en", tr: "環境の影響",                                 q: "How has your environment shaped who you judge?" },
  { t: "無意識に強制する",                                   c: "no",    tr: "Unconsciously imposing on others",           q: "自分の「普通」を押しつけてしまったこと、ある？" },
  { t: "Just because they are different",                    c: "no en", tr: "ただ違うから",                               q: "Has something you once judged ended up changing you?" },
  { t: "他者への誤解を通じて自己を確認する",                 c: "no",    tr: "Confirming oneself through misreading others", q: "誰かを誤解することで、自分について何か気づいたことある？" },
  { t: "Unconscious bias",                                   c: "no en", tr: "無意識の偏見",                               q: "What's a bias you've noticed in yourself?" },
  { t: "Lack of empathy",                                    c: "ny en", tr: "共感力の欠如",                               q: "When do you find it hardest to empathize with someone?" },
  { t: "楽しいから",                                         c: "ny",    tr: "Because it's fun",                           q: "評価することが楽しいと感じる瞬間、ある？" },
  { t: "Because I'm mean",                                   c: "ny en", tr: "意地悪だから",                               q: "Have you ever judged someone and felt bad about it later?" },
  { t: "相対的に強さを持ちたいから",                         c: "ny",    tr: "To feel relatively stronger",                q: "誰かより上に立ちたいと感じるのは、どんな時？" },
  { t: "公平な比較が難しいから",                             c: "ny",    tr: "Because fair comparison is hard",            q: "人を公平に見ることって、本当にできると思う？" },
  { t: "Don't want to mind their own business",              c: "ng en", tr: "自分のことだけ考えたくないから",             q: "Is it ever your business to judge someone else?" },
  { t: "自分のアイデンティティをつくるため",                 c: "ng",    tr: "To form one's identity",                     q: "「自分らしさ」を決めるために、誰かと比べたことある？" },
  { t: "Cause it's fun to do with friends",                  c: "ng en", tr: "友達とやると楽しいから",                     q: "Does judging people feel different when you're with others?" },
  { t: "他人に影響を与えたいから",                           c: "ng",    tr: "To influence others",                        q: "誰かの見方を変えようとしたことある？" },
  { t: "知らないから / わかんないから",                      c: "ng",    tr: "Because they don't know / don't get it",     q: "知らないから評価してしまう——どうすれば変えられる？" },
  { t: "Because they honestly understand some things",       c: "ng en", tr: "本当に理解できることがあるから",             q: "When is judging someone actually helpful?" },
  { t: "For motivation",                                     c: "ng en", tr: "モチベーションのため",                       q: "Has being judged ever pushed you to grow?" },
  { t: "利用したいから",                                     c: "ng",    tr: "To use them",                                q: "人間関係で、使う・使われるって感じたことある？" },
];
